---
kind: pipeline
name: update

trigger:
  branch:
    - main
  event:
    - cron
    - custom
  status:
    - success

steps:
  - name: update
    image: archlinux:base-devel
    pull: always
    commands:
      - pacman -Syu --noconfirm --needed b3sum clang curl git jq libgit2 rust wget
      - sed -i -e 's,exit \$E_ROOT,,' /usr/bin/makepkg
      
      - git clone https://aur.archlinux.org/rlottie
      - cd rlottie
      - makepkg -si --noconfirm
      - cd ..
      - rm -rf rlottie
      
      - ./_update.sh

    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

  - name: notify
    image: drillster/drone-email
    pull: always
    settings:
      host: smtp.migadu.com
      username: noreply@drone.msrd0.eu
      from: noreply@drone.msrd0.eu
      recipients: git@msrd0.de
      recipients_only: true
      password:
        from_secret: SMTP_PASSWORD
    when:
      status:
        - failure

...
