safe: true
keep_files:
  - index.html
  - assets
  - dependencies
  - sources
  - aatree
  - bitmap-font
  - cargo-doc2readme
  - gotham_formdata
  - gotham_formdata_derive
  - gotham_restful
  - gotham_restful_derive
  - hershey
  - influxdb
  - influxdb_derive
  - kicad_newstroke_font
  - log4rs-sentry
  - lottie2gif
  - lottie2webp
  - lottieconv
  - millimeter
  - openapi_type
  - openapi_type_derive
  - rlottie
  - rlottie-sys
  - serde_kicad_sexpr
  - syn-path
