safe: true
keep_files:
  - index.html
  - assets
  - dependencies
  - sources
  - aatree
  - bitmap-font
  - cargo-doc2readme
  - chumsky-branch
  - ellipse-bin
  - gotham_formdata
  - gotham_formdata_derive
  - gotham_restful
  - gotham_restful_derive
  - gotham_restful_redoc
  - hershey
  - heu
